### ISSUE TITLE
Version 23.4 can't be used

### ISSUE THREAD

**Issue by MohamedHeba** [gvenzl/setup-oracle-sqlcl#4]
Hi,
I am not able to use version 23.4, received the below error message.

📦 Download SQLcl
  ✅ Located versions mapper file
  �?� SQLcl 23.4 could not be resolved
  Valid versions are [latest, 23.3.0.270.1251, 23.3.0, 23.3, 23.2.0.178.1027, 23.2.0, 23.2, 23.1.0.089.0929, 23.1.0, 23.1, 23, 22.4.0.342.1212, 22.4.0, 22.4, 22]
  Error: Process completed with exit code 1.

**Comment by aalmiray** [comment]
An update to versions.txt must be made to handle latest versions.
